name: Flutter CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  analyze-test:
    name: Analyze, Test and Build
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: '3.10.6' # Esta versión incluye Dart 3.0.6+, compatible con tu ^3.10.0
          channel: 'stable'
          cache: true # Esto acelerará tus futuros builds

      - name: Enable Flutter web
        run: flutter config --enable-web

      - name: Install dependencies
        run: flutter pub get

      - name: Run Flutter analyze
        run: flutter analyze

      - name: Run Flutter tests
        run: flutter test --no-test-assets

      - name: Build Android APK
        run: flutter build apk --debug

      - name: Build web release
        run: flutter build web --release
